#include "stdafx.h"
#include "uiapplication.h"

#include "include/interface/iuires.h"
#include "src/Atl\image.h"
#include "src/UIObject\Control\control.h"
#include "src/resource/res_bundle.h"
#include "src/Resource\imagemanager.h"
#include "src/Resource\colormanager.h"
#include "src/Resource\fontmanager.h"
#include "src/Resource\stylemanager.h"
#include "src/Resource\layoutmanager.h"
#include "src/UIObject\Window\window_meta.h"
#include "src/UIObject\HwndHost\hwndhost_desc.h"
#include "src/UIObject\Panel\panel_desc.h"
#include "src/UIObject\Panel\ScrollPanel\scrollpanel_desc.h"
#include "src/UIObject\Window\windowbase.h"
#include "src/Util\DPI\dpihelper.h"
#include "src/SkinParse\skinparseengine.h"
#include "src/Util\Gif\giftimermanager.h"
#include "include/interface/iuiautotest.h"
#include "include/interface/iuieditor.h"


