#ifndef UI_SDK_SRC_PROPERTY_PROPERTYID_H_
#define UI_SDK_SRC_PROPERTY_PROPERTYID_H_

namespace ui {

enum UI_SDK_PROPERTY_ID {
  OBJECT_ID = 0,
  OBJECT_PADDING,
  OBJECT_MARGIN,
  OBJECT_BORDER,

  OBJECT_CLASS,
  OBJECT_STYLE,

  OBJECT_WIDTH,
  OBJECT_MIN_WIDTH,
  OBJECT_MAX_WIDTH,
  OBJECT_HEIGHT,
  OBJECT_MIN_HEIGHT,
  OBJECT_MAX_HEIGHT,

  OBJECT_FONT_NAME,
  OBJECT_FONT_SIZE,

  UI_SDK_PROPERTY_COUNT,
};

}

#endif